Responses to reviews
====================

eleddy
======
- adding a new collection, what is allowed users and roles supposed to
  filter on? it doesn't seem to filter on anything
TODO: This filter should allow the end user to create a collection that contains documents on which user 'x' as the View permission.
Portal_catalog checks the View permission for the current user. Maybe we can use unrestrictedSearch if this filter is used.

- It's not entirely clear how to close the drop down for review state. I
  think that I expected to click outside of the drop down and have it
  disappear (onblur).
Fixed in r13665

- Once I add a criteria, then try to add another one that is the same, the
  results end up being a little weird. For example, I have description and
  the word "tomato" with three results. then add another description field
  with no words at all and I get 21 results. I would expect these to be
  an intersection, although I could be wrong since there is no indication.
  I think its just a bug though.
XXX: remove index when used, or merge criteria?

- When using location, if I select relative path and put in a full path, I
  get lots of errors in the logs:
  2010-12-17 17:54:03 ERROR Zope.SiteErrorLog 1292637243.950.54441013414 http://localhost:8080/Plone/@@querybuildernumberofresults
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 47, in call_object
  Module plone.app.querystring.querybuilder, line 52, in number_of_results
  Module plone.app.querystring.querybuilder, line 33, in __call__
  Module plone.app.querystring.querybuilder, line 45, in _makequery
  Module plone.app.querystring.queryparser, line 48, in parseFormquery
  Module plone.app.querystring.queryparser, line 237, in _relativePath
AttributeError: 'NoneType' object has no attribute 'getPhysicalPath'
Don't use a full path in a relative path criteria. I've added a check to prevent that attributeerror in r50222.

- For me the path wording is a little confusing. I think simply renaming
  Path(URL) to absolute path would help, since its the "opposite" of relative
  path
Fixed in r50223

- It would be nice if the query did not submit and filter
  until after the user enters something in the box. I often found myself adding
  a filter and then wanting to see what I had in the live search but it was gone.
  This also makes sense in cases where the filter does not apply to the objects being
  displayed (e.g. event start and end date)
TODO: would be nice.

- Adding a modification date after date "201" triggered an error (was trying to get
  to "2010"). This happened with a lot of dates:
  2010-12-17 17:59:08 ERROR Zope.SiteErrorLog 1292637548.470.755860448 http://localhost:8080/Plone/@@querybuilder_html_results
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 47, in call_object
  Module plone.app.querystring.querybuilder, line 38, in html_results
  Module plone.app.querystring.querybuilder, line 33, in __call__
  Module plone.app.querystring.querybuilder, line 49, in _makequery
  Module plone.app.contentlisting.browser, line 66, in __call__
  Module Products.CMFPlone.CatalogTool, line 325, in searchResults
  Module Products.ZCatalog.ZCatalog, line 656, in searchResults
  Module Products.ZCatalog.Catalog, line 737, in searchResults
  Module Products.ZCatalog.Catalog, line 476, in search
  Module Products.PluginIndexes.DateIndex.DateIndex, line 172, in _apply_index
  Module Products.CMFPlone.patches.dateIndexPatch, line 11, in _convert
  Module Products.PluginIndexes.DateIndex.DateIndex, line 247, in _convert
  Module DateTime.DateTime, line 350, in __init__
  Module DateTime.DateTime, line 643, in _parse_args
  Module DateTime.DateTime, line 1011, in _parse
TimeError: 201
Added a check if preview should be updated in r13666.

- Also nice to have is not to delete the contents of a box if I switch to
  another criteria and then decide to come back. This makes sense if I'm
  trying to decide between using title, description, or searchable text for
  example
XXX: would be nice.

- I'm slightly concerned by the number of requests it takes to return these
  results.
That's not a real problem, right?

- More nice to have is that for items where you have no other choices for the
  type of query (e.g Description "is" versus Locations rel/abs choice) I would
  like to see that be text instead of a drop down. This control makes me wonder
  as the end user if I should check for more options each time and the majority
  of the time I don't need to.
XXX: would be nice.

- I don't think that sorting on title in reverse is a good default. most people
  would expect it to not be reversed. If modification date were selected I would
  agree but I think sortable title is the correct choice here
Fixed in r50225

- What happened to display as table checkbox? If its gone then we need to remove
  the table columns listing. I think this is referring to the display view but
  kinda makes no sense.
This functionality has moved to the 'Display' menu -> 'Tabular view'

- How about this "table of contents" checkbox? From what I can tell it doesn't
  do anything. I'm not too familiar with collections so I could be way off.
Options removed in r50226

- when adding the related to field I immediately get an error:

2010-12-17 18:19:42 ERROR Zope.SiteErrorLog 1292638782.460.265875466564 http://localhost:8080/Plone/@@querybuildernumberofresults
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 47, in call_object
  Module plone.app.querystring.querybuilder, line 52, in number_of_results
  Module plone.app.querystring.querybuilder, line 33, in __call__
  Module plone.app.querystring.querybuilder, line 45, in _makequery
  Module plone.app.querystring.queryparser, line 44, in parseFormquery
AttributeError: 'module' object has no attribute '_referenceIs'
TODO: add parser for referenceIs
Removed related criteria for now in r50227.

- The same issues with * and some unicode as with the p.a.search plip. Must be able to
  handle ParseError: Query contains only common words: '* . In addition, need a way to
  pipe feedback to the user.
I can search just fine for 'འབྲུག་ཡུལ།'.
'Query contains only common words' doesn't happen anymore after adding the checks in r13666.

- When working with adding the collections portlet, instead of saying "search results" it
  would be nice to say "available collections". In general, this portlet ui has me
  wondering what I should actually be doing. what does the "parent" button mean?
That's the default implementation for SearchableTextSourceBinder: out of scope for us.

- Plone.app.collection: Need to have README say something
TODO: make readme

- Plone.app.collection: TODO in collection.py
Removed

- It looks like that in order to add a collection you have to be a manager which I
  think is unnecessarily limiting. At minimum let's integrate it with Site Administrator
  or even Editor. I think add collection portlet sounds like something for the site
  administrator role as well.
Added 'Site administrator' in r50229

- seems to be an extra leading semicolon in querywidget.js. There are lots of errors with
  that js that make me cross browser nervous. Addressing these would make me feel happy
The leading semicolon prevents merging issues when other js files do not close correctly. This is done by default in new files afaik.
Other JSLint issues are addressed.

- The query field widget could use some better documentation.
TODO: documentation.


Conclusion
----------
This UI is really slick. This makes me actually want to use collections. A few things
that must get fixed before merge:
 - must address all the bad user input issues
 - work on the stack traces in all the reviews
 - fix obvious js errors
Those seem all doable and I'm sure this will make a nice addition to the 4.1 release.






rossp
=====
- The README.txt and description in setup.py are empty for
  plone.app.collection, plone.app.querystring, and
  archetypes.querywidget.  These should have some minimal content at
  the very least, preferably they should explain the package for those
  who might want to re-use it.
Duplicate, see above.

- archetypes.querywidget/setup.py only requires plone.app.querystring
  but archetypes/querywidget/configure.zcml includes
  plone.app.vocabularies and plone.app.contentlisting as well.  If
  archetypes.querywidget actually does depend on the ZCML of those two
  eggs, then they should be added as dependencies in setup.py,
  otherwise those ZCML includes should be removed.
This has been resolved.

- Cleaned up a bunch of testing dependency issues.
- Added alltests test-groups eggs.
Thanks!

- plone.app.querystring/setup.py depends on plone.directives.form, but
  I don't see anything that uses it.
This has been resolved.

- The GenericSetup profiles need better titles and descriptions so
  that users can know what they're looking at when installing add-ons.
TODO: fix profile titles

- The results preview is damn cool!  Everything works as it should.
- I love the per-criteria counts, *very* useful.
Thanks!

- The results preview could be a little clearer by saying "3 of 22
  results" instead of just "22 results" and showing only 3.
This was fixed some time ago.

- I think the "Remove line" link in the criteria editing should have
  something to call it out, probably whatever icon we use in Plone for
  deleting/removing, such as a red X.
We don't do icons a lot anymore since Sunburst came out. The link has a class 'removecriteria' which can be used to do extra styling.
IMHO this 

- The criteria value dropdowns don't seem to go away when you click
  elsewhere on the page.
Fixed, see above.

- The criteria value dropdowns are styled differently than other
  dropdowns.
TODO: fix styling for custom widgets

- The date criteria value isn't using a calendar widget nor is any
  description given of how to enter a textual date.  I think this
  might be important enough to be a must-have.

- Since this is meant to be the new canonical Collection
  implementation, shouldn't the Plone default News, Events, and Past
  Events collections use this new implantation when creating new
  sites?

- Fixed some logging issues, was getting *way* too many "... INFO
  plone.app.querystring Generated query: ..." log messages.  Switched
  from INFO to DEBUG.
Thanks!

- Plone handled the following error several times.  This needs to be
  addressed.

    User Name
    admin (admin)
    Request URL
    http://localhost:8080/Plone/@@querybuilder_html_results
    Exception Type
    BadRequest
    Exception Value
    <h2>Site Error</h2> <p>An error was encountered while publishing this resource. </p> <p><strong>Invalid request</strong></p> The parameter, <em>query</em>, was omitted from the request.<p>Make sure to specify all required parameters, and try the request again.</p> <hr noshade="noshade"/> <p>Troubleshooting Suggestions</p> <ul> <li>The URL may be incorrect.</li> <li>The parameters passed to this resource may be incorrect.</li> <li>A resource that this resource relies on may be encountering an error.</li> </ul> <p>For more detailed information about the error, please refer to the error log. </p> <p>If the error persists please contact the site maintainer. Thank you for your patience. </p>
    Traceback (innermost last):

    Module ZPublisher.Publish, line 126, in publish
    Module ZPublisher.mapply, line 72, in mapply
    Module ZPublisher.Publish, line 51, in missing_name
    Module ZPublisher.HTTPResponse, line 741, in badRequestError
    BadRequest: <h2>Site Error</h2> <p>An error was encountered while publishing this resource. </p> <p><strong>Invalid request</strong></p> The parameter, <em>query</em>, was omitted from the request.<p>Make sure to specify all required parameters, and try the request again.</p> <hr noshade="noshade"/> <p>Troubleshooting Suggestions</p> <ul> <li>The URL may be incorrect.</li> <li>The parameters passed to this resource may be incorrect.</li> <li>A resource that this resource relies on may be encountering an error.</li> </ul> <p>For more detailed information about the error, please refer to the error log. </p> <p>If the error persists please contact the site maintainer. Thank you for your patience. </p>

    Display traceback as text

    REQUEST
    form
    cookies
    dtpref_rows	'20'
    zmi_top_frame	''
    dtpref_cols	'100%'
    tree-s	'eJzT0MgpMOQKVneEA1dbda4CI67EkgJjLj0AeGcHew'
    zmi_use_css	'1'
    lazy items
    SESSION	<bound method SessionDataManager.getSessionData of <SessionDataManager at /session_data_manager>>
    other
    AUTHENTICATION_PATH	''
    TraversalRequestNameStack	[]
    LANGUAGE	'en'
    AUTHENTICATED_USER	<PropertiedUser 'admin'>
    URL	'http://localhost:8080/Plone/@@querybuilder_html_results'
    SERVER_URL	'http://localhost:8080'
    LANGUAGE_TOOL	<Products.PloneLanguageTool.LanguageTool.LanguageBinding instance at 0xd8a51cc>
    PUBLISHED	<Products.Five.metaclass.QueryBuilder object at 0xd8a5b0c>
    method	'GET'
    ACTUAL_URL	'http://localhost:8080/Plone/@@querybuilder_html_results'
    URL0	http://localhost:8080/Plone/@@querybuilder_html_results
    URL1	http://localhost:8080/Plone
    URL2	http://localhost:8080
    BASE0	http://localhost:8080
    BASE1	http://localhost:8080
    BASE2	http://localhost:8080/Plone
    BASE3	http://localhost:8080/Plone/@@querybuilder_html_results
    environ
    CONNECTION_TYPE	'keep-alive'
    HTTP_USER_AGENT	'Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.13 (KHTML, like Gecko) Chrome/9.0.597.0 Safari/534.13'
    HTTP_COOKIE	'dtpref_rows="20"; zmi_top_frame=""; dtpref_cols="100%"; zmi_use_css="1"; tree-s="eJzT0MgpMOQKVneEA1dbda4CI67EkgJjLj0AeGcHew"'
    SERVER_NAME	'localhost6.localdomain6'
    GATEWAY_INTERFACE	'CGI/1.1'
    HTTP_ACCEPT	'application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5'
    SERVER_SOFTWARE	'Zope/(2.13.1dev, python 2.6.6, linux2) ZServer/1.1'
    REMOTE_ADDR	'127.0.0.1'
    HTTP_ACCEPT_LANGUAGE	'en-US,en;q=0.8'
    SCRIPT_NAME	''
    REQUEST_METHOD	'GET'
    HTTP_HOST	'localhost:8080'
    PATH_INFO	'/Plone/@@querybuilder_html_results'
    SERVER_PORT	'8080'
    SERVER_PROTOCOL	'HTTP/1.1'
    QUERY_STRING	''
    HTTP_ACCEPT_CHARSET	'ISO-8859-1,utf-8;q=0.7,*;q=0.3'
    channel.creation_time	1291695482
    HTTP_ACCEPT_ENCODING	'gzip,deflate,sdch'
    PATH_TRANSLATED	'/Plone/@@querybuilder_html_results'
This shouldn't be an issue anymore.

- No obviously related errors from bin/alltests that weren't exposed
  with bin/test below.


- ran "bin/test -s plone.app.contentlisting -s plone.app.collection -s
  plone.app.querystring -s archetypes.querywidget" and got the
  following.  This should be addressed:

      Set up plone.app.testing.layers.PloneFixture Traceback (most recent call last):
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 367, in run_layer
        setup_layer(options, layer, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 632, in setup_layer
        layer.setUp()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 110, in setUp
        self.setUpZCML()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 222, in setUpZCML
        loadAll('configure.zcml')
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 217, in loadAll
        xmlconfig.file(filename, package, context=context)
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 653, in file
        context.execute_actions()
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 606, in execute_actions
        callable(*args, **kw)
      File "/usr/local/lib/python/site-packages/Products.GenericSetup-1.6.1-py2.6.egg/Products/GenericSetup/registry.py", line 707, in registerProfile
        raise KeyError, 'Duplicate profile ID: %s' % profile_id
    ConfigurationExecutionError: <type 'exceptions.KeyError'>: u'Duplicate profile ID: Products.CMFUid:default'
      in:
      File "/usr/local/lib/python/site-packages/Products.CMFUid-2.2.1-py2.6.egg/Products/CMFUid/configure.zcml", line 10.2-16.8
        <genericsetup:registerProfile
            name="default"
            title="CMFUid"
            description="Adds UID support."
            provides="Products.GenericSetup.interfaces.EXTENSION"
            for="Products.CMFCore.interfaces.ISiteRoot"
            />


    Running plone.app.collection.tests.base.PACollection:Functional tests:
      Set up plone.app.testing.layers.PloneFixture Traceback (most recent call last):
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 367, in run_layer
        setup_layer(options, layer, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 632, in setup_layer
        layer.setUp()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 110, in setUp
        self.setUpZCML()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 222, in setUpZCML
        loadAll('configure.zcml')
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 217, in loadAll
        xmlconfig.file(filename, package, context=context)
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 653, in file
        context.execute_actions()
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 606, in execute_actions
        callable(*args, **kw)
      File "/usr/local/lib/python/site-packages/Products.GenericSetup-1.6.1-py2.6.egg/Products/GenericSetup/registry.py", line 707, in registerProfile
        raise KeyError, 'Duplicate profile ID: %s' % profile_id
    ConfigurationExecutionError: <type 'exceptions.KeyError'>: u'Duplicate profile ID: Products.CMFDefault:default'
      in:
      File "/usr/local/lib/python/site-packages/Products.CMFDefault-2.2.2-py2.6.egg/Products/CMFDefault/profiles.zcml", line 6.2-11.8
        <genericsetup:registerProfile
            name="default"
            title="CMFDefault Site"
            description="Profile for a default CMFSite."
            for="Products.CMFCore.interfaces.ISiteRoot"
            />


    Running plone.app.contentlisting.tests.base.ContentListing:Functional tests:
      Set up plone.app.testing.layers.PloneFixture Traceback (most recent call last):
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 367, in run_layer
        setup_layer(options, layer, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 632, in setup_layer
        layer.setUp()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 110, in setUp
        self.setUpZCML()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 222, in setUpZCML
        loadAll('configure.zcml')
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 217, in loadAll
        xmlconfig.file(filename, package, context=context)
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 653, in file
        context.execute_actions()
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 606, in execute_actions
        callable(*args, **kw)
      File "/usr/local/lib/python/site-packages/Products.GenericSetup-1.6.1-py2.6.egg/Products/GenericSetup/registry.py", line 707, in registerProfile
        raise KeyError, 'Duplicate profile ID: %s' % profile_id
    ConfigurationExecutionError: <type 'exceptions.KeyError'>: u'Duplicate profile ID: Products.PlonePAS:PlonePAS'
      in:
      File "/home/xen/src/plone-coredev.svn/src/Products.PlonePAS/Products/PlonePAS/profiles.zcml", line 6.2-12.8
        <genericsetup:registerProfile
            name="PlonePAS"
            title="PlonePAS"
            directory="profiles/default"
            description="Extension profile for default PlonePAS setup."
            provides="Products.GenericSetup.interfaces.EXTENSION"
            />

This is resolved

- It seems like the tabular_view has been factored out of the
  standard_view.  They were combined in atct_topic_view and I think
  it's great to factor them out this way.  I see that the "Display as
  Table" checkbox field has also been removed from the collection edit
  form, also good. But this does leave some confusion in play.  From
  the edit form it's not clear what the "Table Columns" field does
  especially since it's help text still refers to the "Display as
  Table" field.  Do we think it's sufficiently clear to just change
  the "Table Columns" help text to refer to selecting the right layout
  from the display menu back on the view screen?
Fixed in r50230

- plone.app.collection, plone.app.querystring and
  archetypes.querywidget are in dire need of comments, docstrings and
  more complete interfaces for developer/maintenance documentation
  purposes.  It's far to difficult to approach and understand how
  things fit together as-is.
TODO: create docs + overview image etc

- Why is a new/separate collection portlet implementation provided in
  plone.app.collection?  Isn't the one in plone.portlet.collection
  already compatible?
p.a.collection is a new implementation with different idioms and a different portal_type.

- The javascriptDisabled validator seems distasteful to me, but I
  might not be understanding it.  Why is this necessary and is there
  really no better way?
TODO: explain in docs why this works the way it does.

- I love how small plone.app.collection is.
Me too!
XXX: convert to Dexterity?

- It sure looks like the archetypes.querywidget.field.QueryField set
  and __init__ methods are entirely unnecessary.
Fixed in r13669

- I don't see any unit tests for the JS.
XXX: explain in docs

- I note that the query builder JS lives in archetypes.querywidget.
  It seems like it would be best to have it factored out into a non-AT
  dependent place.  Would plone.app.querystring be the right place for
  that?
Nope, p.a.querystring should just do parsing the abstracted formquery into a catalog query.

- The test coverage for archetypes.querywidget and
  plone.app.collection looks poor.
Upped coverage to 100%

Conclusion
----------

The implementation is slick and really nice to use.  It's a vast
improvement over what we have currently.  I'd love to see it included
in 4.1.

Having said that I don't think I'm comfortable merging it as-is, but
the changes required seem to be pretty doable.  If more complete
docstrings, comments, and interfaces are added, the test failures are
addressed, and the BadRequest errors are addressed, I'm a strong +1
for merging.
